version: "3.8"

services:
  pdf-merger:
    build:
      context: .
    container_name: pdf-merger-container
    volumes:
      - ./data/source:/app/data/source
      - ./data/target:/app/data/target
    environment:
      SOURCE_FOLDER: /app/data/source
      TARGET_FOLDER: /app/data/target
    ports:
      - "8000:8000"
    command: python app.py
